### ISSUE TITLE
BBB plugins in (Next|Own)Cloud not working

### ISSUE THREAD

**Issue by PhilippKilian** [DE-IBH/b3lb#54]
NC/OC are encoding spaces in the query string by `%20` rather than `+`. Although the BBB API suggests to use `+` BBB also accepts `%20`.

B3lb rejects those requests due how the checksum validation is implemented.

**Comment by liske** [comment]
Cc @schmidtvolker

**Comment by kaystrobach** [comment]
ohh - thanks a lot - just asked my fellows at schullogin to send you the credentials. Will check right now.

**Comment by kaystrobach** [comment]
I think this patch is not deployed yet - right? I'm still getting the error. Will check later this week again.

**Comment by kaystrobach** [comment]
BTW. Does it make sense to patch the original BBB API Plugin of nextcloud? Maybe suggesting to use the standard PHP BBB API?

https://github.com/bigbluebutton/bigbluebutton-api-php

https://github.com/sualko/cloud_bbb/blob/af952b4cb0605d9445c2fbf709c05920f03e4762/composer.json#L13

**Comment by liske** [comment]
> I think this patch is not deployed yet - right? I'm still getting the error. Will check later this week again.

We are going to make a intermediate deployment for bbbconf.de this evening. We used another NC instance for debugging and validating the patch.

**Comment by liske** [comment]
> > I think this patch is not deployed yet - right? I'm still getting the error. Will check later this week again.
> 
> We are going to make a intermediate deployment for bbbconf.de this evening. We used another NC instance for debugging and validating the patch.

The intermediate deployment is online!

**Comment by kaystrobach** [comment]
Woohoo works … more testing tomorrow!
